### ISSUE TITLE
Post-Mother Brain/Escape seems to be able to require player to use ammo (Green Gate)

### ISSUE THREAD

**Issue by ScorelessPine** [blkerby/MapRandomizer#1]
# Settings
Generated ROM filename (if available):
smmr-v1-480400005-88365281716750872325926485397485.sfc

# Describe the bug
After killing Mother Brain, the player typically does not have any ammo available because of the Rainbow Beam attack. In the seed shown, the first room after killing Mother Brain requires you to shoot open a Green Gate before you have the ability to farm any ammo from enemies. I'm at least 90% sure that there isn't some strat in "Caterpillar room" or Red Tower Elevator Room to get one of those caterpillars close enough to grab a super from them through the gate with grapple, even though I had canBePatient on. If I'm wrong though, I'd be happy to learn.

![image](https://user-images.githubusercontent.com/28274052/207012169-b8c41f28-d3ec-4731-afac-2b132f9f6784.png)

**Comment by blkerby** [comment]
Ah, that's right. This is a problem. Right now the randomizer logic stops after collecting the last progression item, which means it doesn't consider what happens after the Mother Brain fight. We're thinking about solving this by hacking the ROM to allow Hyper Beam shots to open gates and destroy Super/PowerBomb blocks.

**Comment by beauxq** [comment]
My first seed also ran in to this problem.
The entrance to Kraid's lair (with super blocks) was directly behind mother brain.

**Comment by blkerby** [comment]
We ended up fixing this now by modifying Mother Brain's rainbow beam not to drain ammo, the same solution used in World Randomizer. Thanks to IronRusty for the suggestion, and to Aremath for the patch in World Randomizer which we reused here.
