### ISSUE TITLE
Moonfall can't be triggered by moonwalking and tapping jump

### ISSUE THREAD

**Issue by Phoenix100k** [blkerby/MapRandomizer#105]
# Settings
Seed URL (or ROM filename): map-rando-2h77n5Lvp.sfc (and) map-rando-LpcDwyrWy.sfc

# Describe the bug
Typically, I'm able to initiate Moonfall by moonwalking toward a ledge and tapping jump to initiate a downward spin jump in the other direction from where I'm facing. Since the 10-16-2024 update, the same action now makes Samus turn around and execute a regular-height jump. I can't seem to engage Moonfall the way I used to.

BEFORE:
https://github.com/user-attachments/assets/648225e9-8ef6-4724-bbd5-b82af3504166

AFTER:
https://github.com/user-attachments/assets/7f0fee37-4c31-4889-8b60-4fbcd21132b3

**Comment by blkerby** [comment]
It appears that this was a bug in the old version of the Respin patch, prior to the v114 update. In the vanilla game, it's not possible to initiate a moonfall in that way. After the update, the behavior of the randomizer aligns with the behavior of the vanilla game, which is what we want. To initiate a moonfall now, you'll need to be holding an angle button (angle up or angle down). See the Wiki for more information: https://wiki.supermetroid.run/Moonfall.
