### ISSUE TITLE
Glitched metroid cutscene

### ISSUE THREAD

**Issue by aquanight** [blkerby/MapRandomizer#12]
**Symptoms**:
Transition into Big Boy Room from Kraid results in glitched metroid cutscene.

**Steps to Reproduce**:
Version 49
Seed: https://maprando.com/seed/U_zxQ3j3JbhF8kyG0m2mkw/
Load this save state using SNES9x: [map-rando-U_zxQ3j3JbhF8kyG0m2mkw.zip](https://github.com/blkerby/MapRandomizer/files/11070560/map-rando-U_zxQ3j3JbhF8kyG0m2mkw.zip)

This save state should load the player immediately after having defeated Kraid (having entered from the left).
The door on the right leads to Big Boy Room
The issue is reproduced when crossing this door.

**Expected Results**
Metroid cutscene should not occur and player should be able to proceed through the Big Boy Room from left to right.

**Actual Result**
Instead of bypassing the metroid cutscene, the following incorrect behavior occur:
- The player is unable to shoot the debris blocking the entry.
- The Baby is observed entering the field, chasing the sidehopper in the background.
- Eventually, the Baby begins its chase after the player. Being trapped by the debris, the player is inevitably caught and drained to 1 Energy as usual.
- When this occurs, the field will appear to "overscroll" past the left exit. The player can't actually enter that area because they will reach the exit transition and return to Kraid's chamber.
- These events will repeat each time the Big Boy Room is entered, thus preventing the player from proceeding this way.

**Comment by blkerby** [comment]
Thanks for the report! I was able to reproduce the issue and am digging into it now.

**Comment by blkerby** [comment]
It appears to be an issue with the "fast doors" quality-of-life option. Still digging into it, but in the meantime, I regenerated your seed with that option turned off: https://maprando.com/seed/6Hrh68OKYRvHgwYsJRr3aA/. Using that, you should be able to continue playing from your save state if you'd like.

**Comment by blkerby** [comment]
Fixed now in v50. For details, see discussion on MetConst: https://discord.com/channels/127475613073145858/371734116955193354/1089645631523524790
