### ISSUE TITLE
Bugged Reservs

### ISSUE THREAD

**Issue by ricardokaora** [blkerby/MapRandomizer#18]
# Settings
Seed URL (or ROM filename):
map-rando-lYPVZq3tWc77oVpX2NBHUw

# Describe the bug
Reserve tanks are bugged. I got 3 reserve tanks on manual mode. When I tried to use one of them, the 3 got depleted.
I did some testing and got hit for a little bit of damage. I had almost full energy (96) and tried to fill up to 99. When I used the reserv tank I got to 99 but all 3 reserves got depleted.

(PS: English is not my first language, I hope I made myself clear)

**Comment by blkerby** [comment]
Thanks for the report. This seems to be a vanilla game bug, not specific to the randomizer. In general we leave quirky behavior of the vanilla game intact, so I don't think we'll fix this one. But it may be worth considering as part of a quality-of-life option in the future.
