### ISSUE TITLE
unbeatable seed - metroid room 4 logic

### ISSUE THREAD

**Issue by beauxq** [blkerby/MapRandomizer#4]
# Settings
Generated ROM filename (if available): smmr-v5-1909176377-464593966782127806984477131014152

# Describe the bug

It expects me to get through metroid room 4 with nothing, on medium skill.
I have doubts about whether even an expert could do it.

**Comment by blkerby** [comment]
Right, the sm-json-data has this as [free](https://github.com/miketrethewey/sm-json-data/blob/90205f359cf203bd3e979ef382ae5e5a542400fc/region/tourian/main.json#L957), which is certainly incorrect. I think the reason for this is an assumption that the requirements would be encompassed by the gray door lock on node 2; however, for Map Rando the gray door is gone so the lock requirements are ignored. We can fix this by adding explicit strats on the link from 1 to 2. 

I believe this sort of problem may happen with many rooms having gray door locks, so we should go through and check all of them.

**Comment by blkerby** [comment]
Fixed by #451.
