### ISSUE TITLE
Potential Softlock in the Escape Sequence

### ISSUE THREAD

**Issue by Rivers24** [blkerby/MapRandomizer#5]
# Settings
Generated ROM filename (if available): smmr-v14-619243965-1166397081153765026062685721888008

So, not exactly a guarenteed softlock, but something to maybe look into. If you have the spore spawn fight right after mother brain, with you coming from the top, you get stuck if you havent killed him before. Admittedly could have been fine if I killed him first, but I was just looking for the bosses since I had everything I needed to beat the game, so didnt really explore this area very much when I saw no bosses here other then mother brain.
![bsnes_lCJetBj01e](https://user-images.githubusercontent.com/118337441/209721580-410e5ad3-db4a-4ee8-b1b2-e1b19197dc1b.png)
![bsnes_LixY430UXR](https://user-images.githubusercontent.com/118337441/209721630-d9e7cc11-efae-43fd-be17-fb91690634ad.png)

**Comment by blkerby** [comment]
This should be fixed in version 19, as we now de-spawn bosses & enemies during the escape.
