### ISSUE TITLE
Idea/Request: PC version

### ISSUE THREAD

**Issue by jtfen86** [blkerby/MapRandomizer#57]
Is it known in the community that a PC version of SM exists (doesn't include the rom, obviously)? Here is the repo for those that don't: https://github.com/snesrev/sm

Forewarning: I don't have any programming knowledge. Would anyone working on the map rando be willing to fork it and integrate this project with it? I imagine that there must be some things that could be done in a PC native client that an emulator couldn't do. Or at the very least modify it to where generated roms would work with it?

**Comment by blkerby** [comment]
I was aware that there was a PC version under development but don't know much about it. Part of the basic philosophy of the Map Rando project is that, aside from the map randomization, we try to stick with the vanilla feel and behavior of the game as far as reasonably possible. We have quality-of-life options to make the game more playable, but we try to keep these somewhat minimal. At the moment, I'm not really seeing a need for us to go beyond what an SNES can do (aside from MSU-1 support, which is already included). Supporting other targets aside from SNES would add a lot of complexity, so it would only make sense to do if there were a strong reason for it. At the moment, I'm not seeing one.

Of course, anyone who is interested would be welcome to fork the project and give it a try.
