### ISSUE TITLE
Seed smmr-v28-961155752-3629640346891478804133038260240 doesn't seem to be solvable

### ISSUE THREAD

**Issue by Spike1978** [blkerby/MapRandomizer#6]
Spoiler log states:

"step": 3,
      "flags": [
        {
          "flag": "f_ShaktoolDoneDigging",
          "area": "Crateria"
        }

But how can shaktool be done digging without me getting PB's first?

**Comment by blkerby** [comment]
In the game the flag for Shaktool done digging is set by exiting the room from the right side. So if you can reach the right side of the room, you can enter, exit, and re-enter to open up the path without PBs, and the logic can require this. This behavior comes from the vanilla game, though the implications in Map Rando are confusing and we are planning on changing this in the future.

**Comment by Spike1978** [comment]
Ok, it works yes. You don't need to change that just be sure to mention that behaviour on your website under Things to know cause that was where is looked first. Closing issue thanks.
