### ISSUE TITLE
the logic surrounding the glass tube does not seem to be functioning properly.

### ISSUE THREAD

**Issue by suspended7th** [blkerby/MapRandomizer#8]
# Settings
https://maprando.com/seed/iL8hWihjXLRKsxK-iWzXvw/

# Describe the bug
The json list of what should be possible is not accounting for the glass tube properly.  very early on, it states I should be able to get the space jump from the right sand pit, then go defeat draygon.  but due to the glass tube existing, I cannot get over to draygon.  It requires me to go through the left sand pit.  The only clip I am aware of for the glass tube was from the top to the inside using morph ball which I don't have.  And xray climbing could possibly be used to go from the door at the bottom into the pipe. 

Going the path described in the solution json would require me to clip from beneath the pipe into the pipe with only gravity suit and missiles.

I deeply apologize if there is a clip there that I am unaware of.  but as it stands with no way to get into that pipe, the logic is broken.  This isnt super important for this seed as I can still go fight draygon, but it could be important in other seeds.

**Comment by suspended7th** [comment]
welp.....  I guess this was fixed right after I rolled the seed.....

**Comment by blkerby** [comment]
Thanks! Yeah this was a recently introduced bug and by chance this time we happened to catch it just before. The report is much appreciated, so please continue sending these our way if you notice anything else that seems wrong.
