### ISSUE TITLE
Tattoo ROM with map rando identifier and seed information

### ISSUE THREAD

**Issue by ryannewington** [blkerby/MapRandomizer#80]
It would be great for integrations via fxpak/sd2snes/usb2snes to be able to 

1) Positively identify a map rando ROM by reading an known value from a known memory address
2) Be able to have a mechanism to determine the logic mode (basic/medium/hard/extreme) used to create the map rando. We discussed on discord having the seed name retrievable from the ROM, and able to be used to look up the settings via HTTP.

**Comment by blkerby** [comment]
Addressed this now in https://github.com/blkerby/MapRandomizer/commit/9ac43b22fe7101132ad81110e01c1f633bc14a36.

**Comment by ryannewington** [comment]
Tested and looking great!
