### ISSUE TITLE
botwoon hallway logic

### ISSUE THREAD

**Issue by donadavs** [blkerby/MapRandomizer#9]
Hi, I encountered a seed where i didn't have gravity or high jump and was expected to mochtroid ice clip going from right to left in the botwoon hall. the problem is none of the moctroids are accessible without gravity or high jump. the one that seems most reachable is impossible to get to even with a good crouch jump.

**Comment by kjbranch** [comment]
It looks like this is possible with just crouch jump and down grab. 
- Use those to get onto the platform on the left.
- Get on the rightmost spot, to where Samus is mostly hanging off the edge.
- Crouch jump and press over such that you don't bonk the ceiling, but also don't spin jump.
- Down grab onto the platform to the right.

Currently all the logic requires is `canMochtroidIceClip` and `canSuitlessMaridia`. I will add the crouch jump, down grab, and a careful jump to it.
